version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: shamir
      POSTGRES_PASSWORD: shamir@123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shamir"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - hostapp-db:/var/lib/postgresql/data

  server-container:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "npx typeorm migration:run && node dist/index.js"
    ports:
      - "3000:3000"

volumes:
  hostapp-db:
